### ISSUE TITLE
Cordova 4 update

### ISSUE THREAD

**Issue by lilinfr** [becvert/cordova-plugin-zeroconf#1]
Hi !

cordova-plugin-zeroconf was perfectly woking until I upgraded to cordova 4.
It seems to have also upgraded swift. Now at runtime I have a crash here: ZeroConf.swift:52.
`publishers[fullType + "@@@" + name] = publisher`

Im absolutly not fluent in swift, so I dont know why it is broken :)

**Comment by lilinfr** [comment]
Can also crash here: ZeroConf.swift:41
`        let dict = command.arguments[3] as! [String: String]`

> Could not cast value of type 'NSNull' (0x1e536a0) to 'NSDictionary' (0x1e53394).

**Comment by becvert** [comment]
Hi lilinfr!
It has not been tested on cordova-ios@4 yet.
I'm still using 3.9.2 but was planning to upgrade in the next few days.
So I'll try to provide a fix as soon as I can.
Thanks

**Comment by lilinfr** [comment]
Thanks. 

Im trying to fix it by myself, but im feeling underpowered about swift :)
I think the second issue (command.arguments[3]) can be fixed with this:
`if let dict = command.arguments[3] as? [String: String]`
(since it is optional)

**Comment by becvert** [comment]
Please upgrade and give me feedback then we'll close this issue

**Comment by lilinfr** [comment]
Thanks ! Seems ok now
