### ISSUE TITLE
watch() never finds anything in my network on Android

### ISSUE THREAD

**Issue by mishoboss** [becvert/cordova-plugin-zeroconf#12]
Hello,
watch() function never returns a result. Even if I try `.zeroconf.watch('local.', function(result) {` and there a lot of services on my local network. Other Android Bonjour apps find these services without problems.

This is Android 6.0.1

**Comment by becvert** [comment]
anything with `_http._tcp.local.` or `_tcp.local.` or `.local.` ?

**Comment by emcniece** [comment]
Testing this right now, and I do get results for `cordova.plugins.zeroconf.watch('_http._tcp.local.', console.log)`. I initially thought that there were no results at all, but now it seems like I simply do not understand the `type` query.
