### ISSUE TITLE
Could you add a 'fail' property on the ZeroConf interface.

### ISSUE THREAD

**Issue by NeoLSN** [becvert/cordova-plugin-zeroconf#15]
Currently, I want to send an error event when the ZeroConf is down, but there is no interface let me put or replace the failure function. I can only see the error happen on the console but nothing I can do. So could you please add a fail property like [cambiocreative](https://github.com/cambiocreative/cordova-plugin-zeroconf/blob/master/www/zeroconf.js) do?

**Comment by NeoLSN** [comment]
I also suggest ionic-native should support your plugin. See https://github.com/driftyco/ionic-native/issues/636.
So it might needs your plugin provide success and fail callback on the interface.

**Comment by becvert** [comment]
That sounds good. I'll do that. Thanks

**Comment by becvert** [comment]
Master branch's been updated.
Please tell me if that's fine with you.

**Comment by NeoLSN** [comment]
Great job. Just waiting for new release.

**Comment by NeoLSN** [comment]
Will you release 1.2.0 to npm?

**Comment by becvert** [comment]
Yes I will. I'd like to release it this week.
I made some other improvements that I want to test properly before.
Plus I'm just caught up in some other stuff right now.

**Comment by becvert** [comment]
done
