### ISSUE TITLE
No error callback in watch

### ISSUE THREAD

**Issue by bartpeperkamp** [becvert/cordova-plugin-zeroconf#18]
Thanks for creating this plugin, i've been looking for it for quite a while! However, i am unable to check if a certain device is present. If the the service is not found, i cannot get an error or timeout event. Can you help me?

zeroconf.watch('_customservice._tcp.local.', function(result) {
      var action = result.action;
      var service = result.service;
if(!result) {
//do something here
}
      if (action == 'added') {
          console.log('service found', JSON.stringify(service.addresses[0]));
      } else {
          console.log('something else');
      }
    });

or

zeroconf.watch('service._tcp', function(succes, error) {
// etc.
}

or zeroconf.watch('service._tcp')
.then, function (data) {
//etc
}
.catch, function(error) {
}

Would that be possible?

**Comment by becvert** [comment]
Next version of the plugin is coming up soon.
Success and Failure callbacks included.

But it isn't the purpose of ZeroConf to say if a device is present or not.
The plugin just watches for properly advertised services.
So there might not be an error at all in your case.
A timeout might be used at the application level. That's your responsability and not the plugin's one.

**Comment by bartpeperkamp** [comment]
Thanks, yes, i figured that out. I'll close this issue.
