### ISSUE TITLE
[iOS] "OBJC_CLASS$_Hostname" not found

### ISSUE THREAD

**Issue by bartpeperkamp** [becvert/cordova-plugin-zeroconf#19]
I keep getting this error, no matter what i try:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_Hostname", referenced from:
      objc-class-ref in ZeroConf.o
ld: symbol(s) not found for architecture x86_64

Any clue as to what is happening?

**Comment by becvert** [comment]
You must add the `Hostname.m` file to your target.
I don't know why it is not added automatically.

**Comment by bartpeperkamp** [comment]
That works, thanks. However, i can't build the project using Ionic. I tried creating a blank project and adding the plugin, but it fails with the same reason.

**Comment by bartpeperkamp** [comment]
That worked, my new (Swift?) error is this:

fatal error: unexpectedly found nil while unwrapping an Optional value

**Comment by becvert** [comment]
Have yout got more details on this new error? a line number or something?

**Comment by bartpeperkamp** [comment]
I cannot find the line number, here is a screenshot.

![screen shot 2016-11-10 at 11 48 03](https://cloud.githubusercontent.com/assets/1607752/20173933/bd59e2fe-a73b-11e6-862f-ce069b9d8bd8.png)

**Comment by becvert** [comment]
Thanks for the screenshot.
How do you call the watch function?
like this for instance `zeroconf.watch('_http._tcp.', 'local.', success)`?
domain ('local.') is now a separate argument.

**Comment by bartpeperkamp** [comment]
I think that was it. However, i wrapped it in a deviceready event, so it might still be that. I'll test it and let you know.

**Comment by gercho25** [comment]
The problem is in the file: "plugin.xml":

You have to change:
`<header-file src="src/ios/Hostname.m"/>`
By:
`<source-file src="src/ios/Hostname.m"/>`

**Comment by becvert** [comment]
How could I not see that!
Thank you very much @gercho25

**Comment by gercho25** [comment]
Hi,

Do you plan to correct the plugin and update the repository in the next few
days?
It is to know if I expect correction or not.

Best regards
German


2016-11-17 5:21 GMT-03:00 becvert <notifications@github.com>:

**Comment by becvert** [comment]
I'll fix this right away :smile:

**Comment by becvert** [comment]
done

**Comment by bartpeperkamp** [comment]
Good job, thx! :) This makes it a little more clear. I hope this plugin get's in the list of plugins for Ionic2. It's pretty awesome!
