### ISSUE TITLE
Bad_access error in watch function on IOS

### ISSUE THREAD

**Issue by wanjungao** [becvert/cordova-plugin-zeroconf#2]
watch function caused Bad_access error. It appears that the browsers object is not allocated at the time when a new browser is added.

`

func watch(command: CDVInvokedUrlCommand) 
.............
        browser.commandDelegate = commandDelegate
        browser.watch()
  >       browsers = [String: Browser]()    < added  this line, fixed the issue.
       
 browsers[fullType] = browser
`

**Comment by becvert** [comment]
Hi wanjungao!
which version of cordova-ios are you using?

**Comment by wanjungao** [comment]
6.0.0

**Comment by becvert** [comment]
assuming same issue as #1

**Comment by becvert** [comment]
it looks like the variables should be instantiated in the pluginInitialize method

```
override func pluginInitialize() {
    publishers = [:]
    browsers = [:]
}
```

**Comment by becvert** [comment]
Please upgrade and give me feedback then we'll close this issue

**Comment by wanjungao** [comment]
It seems working now. (I have to remove platform and add it back to make the changes appear.)

Thanks!
