### ISSUE TITLE
After update 1.2.1 slow discovering

### ISSUE THREAD

**Issue by JulianGarciaCastillo** [becvert/cordova-plugin-zeroconf#20]
After update to 1.2.0, discovering services takes almost 10 seconds, last version (1.1.3) was almost instantly.

**Comment by becvert** [comment]
Android or iOS or both?

**Comment by JulianGarciaCastillo** [comment]
I'm testing on Android, I'll let you know when I try on iOS

**Comment by JulianGarciaCastillo** [comment]
There is no delay on iOS 10, only android.

**Comment by becvert** [comment]
Android is often slower than iOS.
You saw a difference on Android between 1.1.3 and 1.2.1?

**Comment by JulianGarciaCastillo** [comment]
Yep, that is the weird thing. On 1.1.3 services appeared right at the moment, but now (since 1.2.0), it takes from 5 to 25 seconds. So far it looks like it's happening only to me since nobody has said anything, but all I did was update it so I don't know what can be.
PD: I'm using ionic 2.

**Comment by geesen** [comment]
I also updated to 1.2.1 and now android is not working anymore (iOS is fine). No services are found (I tested also with different types from different hosts).

Tested on Android 6.0 and 4.2.2.

**Comment by becvert** [comment]
Please try 1.2.4.
Closing for now

**Comment by JulianGarciaCastillo** [comment]
After updating to 1.2.4 it takes about 8 seconds to find services first time, after that (doing 'unwatch' and then 'watch'), it's instant. So I can say it's working better.

**Comment by beaubrewer** [comment]
I see it taking ~8-10 seconds as well. This takes it off the table for me as an option from a usability standpoint. I would love to see it sub 3 seconds.

Any thoughts?

**Comment by julianCast** [comment]
Ok, now with the new 1.2.7 version discovering services on Android is WAY faster, I mean like 2 seconds. 
Great Job **becvert** !
