### ISSUE TITLE
[iOS] Adobe phonegap cloud build error

### ISSUE THREAD

**Issue by pensan** [becvert/cordova-plugin-zeroconf#21]
Since a couple of days I get the following error when trying to build my app for iOS.

> Check dependencies
Not running swift-stdlib-tool: ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES is enabled, but the product type 'Static Library' is not a wrapper type.

> [...]

> Check dependencies
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.
“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.

> ** BUILD FAILED **

> The following build commands failed:
	Check dependencies
(1 failure)

Used plugins:

> Installing "cordova-plugin-add-swift-support" at "1.6.0" for ios
Installing "cordova-plugin-device" at "1.1.4" for ios
Installing "cordova-plugin-console" at "1.0.5" for ios
Installing "cordova-plugin-whitelist" at "1.3.1" for ios
Installing "cordova-plugin-splashscreen" at "4.0.1" for ios
Installing "cordova-plugin-statusbar" at "2.2.1" for ios
Installing "ionic-plugin-keyboard" at "2.2.1" for ios
Installing "cordova-plugin-zeroconf" at "1.2.1" for ios

PhoneGap (iOS / Android / Windows):

> cli-6.3.0 (4.2.0 / 5.2.1 / 4.4.1)

Is this something Adobe has to fix? The build is successful if the zeroconf plugin is removed form the config.xml

**Comment by becvert** [comment]
Did version 1.2.1 use to work with phonegap before a couple of days?
I don't use phonegap so I'm not familiar with it, and don't provide any specific support,
but first I would check that phonegap is working with Swift version 3.0

**Comment by pensan** [comment]
Yes, 1.2.1 worked just fine.
I also tried all available versions (1.0.1 - 1.2.1) but no luck. Also tried to build with newer (6.3.1 & 6.4.0) versions of the cli (https://build.phonegap.com/current-support)

Unfortunately I don't have a local iOS build setup to test if its working outside of PhoneGabBuild.

**Comment by becvert** [comment]
There has been a XCode update very recently I believe, 8.2.
I may need to update the plugin. 
I'll try to do that over the weekend.

**Comment by pensan** [comment]
that would be awesome, thank you :)

**Comment by pensan** [comment]
I also opened an issue on the Adobe forums: https://forums.adobe.com/message/9212372
It seems the problem is related to their service and not your plugin.
