### ISSUE TITLE
Send data

### ISSUE THREAD

**Issue by MrShakes** [becvert/cordova-plugin-zeroconf#23]
Forgive me if it's in here somewhere but I've played with it and can't seem to crack it, is there a way to send and receive data via the ipv4 Address. I keep trying to connect to the http://{ipv4Address}:{port} but can't and then I'll need to send and receive data. I read up about using tcp here: http://rossmartindev.blogspot.com.ng/2012/12/my-phonegap-bonjour-plugin-it-can.html. 

Is there a way to do this please?

**Comment by becvert** [comment]
This plugin is about discovering devices on a network.
To exchange data you could use [cordova-plugin-websocket-server](https://github.com/becvert/cordova-plugin-websocket-server)
