### ISSUE TITLE
Discovering all services

### ISSUE THREAD

**Issue by Cowprod** [becvert/cordova-plugin-zeroconf#24]
Hi,

The plugin works great to discover service by known types, for example

zeroconf.watch('_http._tcp.', 'local.', function(result) { ... 

It works perfectly on android and ios.

But is there a way to discover for exemple all _tcp. services ?

I tried:

 zeroconf.watch('_tcp.', 'local.', function(result) { 

...nothing

Any idea ?

Regards,

**Comment by becvert** [comment]
Hi,
I don't know if `_tcp.` alone is allowed by the protocol.
Could you try `_services._dns-sd._udp.` as it seems to be a special type to query all services.

**Comment by Cowprod** [comment]
I try this tonight !

**Comment by Cowprod** [comment]
nothing more, I wanted to list all services to see if I can find my custom type created by https://www.npmjs.com/package/bonjour 
ex: _myType._tcp. itdoes not work too, if I change the type to http it works.

I'm going to search a little with command line tools

**Comment by becvert** [comment]
OK. I'll do my own tests tomorrow.

**Comment by Cowprod** [comment]
In fact it works !
I saw my custom service but after a very very long time (may be 5 minutes) on an android tab.
After killing and relaunching the app the services appear after 15/20 seconds

I'm still waiting to see it on my iphone...

I think I saw a similar issue so you may close this one

thank you for all

**Comment by Cowprod** [comment]
Hi, this morning I tried to publish the service via avahi instead of the nodejs bonjour module (npm bonjour) and both ios and androïd devices find it in a very short time.
Sorry for the noise ! and thanks for all
