### ISSUE TITLE
 cordova-build error

### ISSUE THREAD

**Issue by Matheus-Garbelini** [becvert/cordova-plugin-zeroconf#25]
Hello, i'm trying to compile your plugin with cordova in visual studio and I'm getting this error:
```C++
 Executing "after_prepare"  hook for all plugins.
1>  Resolving module name for cordova-lib/src/cordova/platform_metadata => ../cordova/platform_metadata
1>  Resolving module name for glob => glob
1>MSBUILD : cordova-build error : TypeError: undefined is not a function
```

I can't find this error. Do you knowwhat could it be? I'm using the last version of cordova i think

**Comment by becvert** [comment]
No idea. Without the plugin it compiles fine?

**Comment by Matheus-Garbelini** [comment]
Yes, I'm using Cordova 6.1.1

**Comment by becvert** [comment]
Are you trying to build for the Windows platform?
This is a Android and iOS plugin only.

**Comment by Matheus-Garbelini** [comment]
No, I,m trying to build to Android only

**Comment by Matheus-Garbelini** [comment]
I will zip the project and post her to you

**Comment by becvert** [comment]
OK. But I sense that it's an issue with MSBUILD (i.e. Visual Studio?)
I'm not using it so I'll let you figure this out I think as I have no issue with Android Studio and XCode.
Please when you solve your problem, tell us. Thanks

**Comment by amirmatin** [comment]
Hi, I have the same issue with cordova cli --v 6.1.1. tried upgrading diferent cli versions 5.3.3 and 6.2.0 but have the same issue..

thanks
