### ISSUE TITLE
[Browser] Any interest in a browser version?

### ISSUE THREAD

**Issue by emcniece** [becvert/cordova-plugin-zeroconf#27]
Currently I am using a small mock server to produce mDNS query results during browser-based development. It does look like I could convert this standalone service into a package that could be used inside this plugin.

Functionality might not be identical, but it would at least give us something to work with during local development.

Would this be useful for anyone else?

**Comment by becvert** [comment]
Please feel free to fork and propose a Pull Request. We'll see then.

**Comment by beaubrewer** [comment]
I would find it helpful. It would speed development up.

**Comment by predorock** [comment]
:+1:

**Comment by becvert** [comment]
Closing old issue. Feel free to reopen.
