### ISSUE TITLE
Doesn't work for watching/Listening service from mobile hotspot network.

### ISSUE THREAD

**Issue by GanuM** [becvert/cordova-plugin-zeroconf#28]
Hi,
  I am using https://www.npmjs.com/package/bonjour to publish a http service, but zeroconf on android doesn't see's this.
  when use the bonjour npm client on my machine I could see the service being broadcasted. Please give a fix asap, by the way, thanks a lot for this plugin.

**Comment by becvert** [comment]
Do you mean that your android device is configured as a private hotspot/tethering mode?
and the machine broadcasting the http service is connected in wifi to that android device?

**Comment by saichaitanyaeruvaram** [comment]
Yes, if the machine broadcasting the http service is connected in wifi to that android device (mobile hotspot), zeroconf doesn't detect the http service.
