### ISSUE TITLE
Service aren't added on iOS

### ISSUE THREAD

**Issue by fttx** [becvert/cordova-plugin-zeroconf#30]
I use [this](https://github.com/watson/bonjour) library to announce my service on a Windows 10 machine.

If i use an Android phone it works, while if i use an iPhone the service is never listed as "added", and i get a "removed" message after several minutes.

![image](https://cloud.githubusercontent.com/assets/5663423/24588589/609d8682-17cb-11e7-89c6-dc5be07d4075.png)

If i use an macOS machine to announce the service it works on both Android and iOS

**Comment by becvert** [comment]
I can see that other services are added, so this plugin seems to work in part.
Could you try another library to announce your service, just to make sure who's the culprit here.

**Comment by fttx** [comment]
I tried https://github.com/agnat/node_mdns and worked ¯\_(ツ)_/¯

**Comment by emcniece** [comment]
@fttx did you test this on native platforms as well?

**Comment by emcniece** [comment]
@fttx how exactly did you include this in your project? You have this running on iOS and Android platforms? Are you using Ionic 1, 2 or 3?

**Comment by fttx** [comment]
Yes, i had it running on both iOS end Android, i don't remember exactly how i added it, but for sure the ionic-native module wasn't available yet, see here: https://github.com/fttx/barcode-to-pc-app/tree/ff1f125a8881a4146fa1ac99f8cc367baeb3bdce

**Comment by LabDeve** [comment]
I've the same problem...
