### ISSUE TITLE
[iOS] Crash, if service txtRecordData is malformed

### ISSUE THREAD

**Issue by fishkingsin** [becvert/cordova-plugin-zeroconf#32]
I have a device broadcasting null value dictionary
cause crashed in
https://github.com/becvert/cordova-plugin-zeroconf/blob/master/src/ios/ZeroConf.swift#L354

**Comment by becvert** [comment]
ok. does it work on Android?

**Comment by fishkingsin** [comment]
it is ios specific issue

**Comment by becvert** [comment]
Please test version 2.1.4

**Comment by fishkingsin** [comment]
I found that in txtRecordData is raw byte data to translate it to dictionary it need a proper key,value pair format

but some of my device boardcasted 

Optional("\u{0E}isPaired=false\u{0C}serialNumber\rmodel=MODEL_NAME")

serialNumber(key) was wrong format 
"=" is missing 
"value" is missing

**Comment by becvert** [comment]
so txtRecordData returns some data but it is malformed key/value pairs?

are you able to do a quick check on android too? that would be nice.

**Comment by becvert** [comment]
Does it still crash the app by the way?

**Comment by fishkingsin** [comment]
it will crash
seem NSDictionary could not parse the malformed data

**Comment by becvert** [comment]
[NetService.dictionary fails an assertion if txtData cannot be represented as an NSDictionary object](https://developer.apple.com/reference/foundation/netservice/1408164-dictionary)

failed assertions terminate the app in debug for sure, but maybe not in production. @fishkingsin , does it crash in production?

if it does, the problem is in Swift you cannot catch a failed assertion.
that means we need to parse ourselves the data. I do not want to do that.

**Comment by fishkingsin** [comment]
@becvert  thanks for the comment, I will trying to fix that

**Comment by becvert** [comment]
What's the status on this @fishkingsin

**Comment by fishkingsin** [comment]
I think it only happen from my case, ios + melform txtData

**Comment by becvert** [comment]
No worries. I'll have another look later on.

**Comment by fishkingsin** [comment]
some finding
https://stackoverflow.com/questions/40193911/nsnetservice-dictionaryfromtxtrecord-fails-an-
assertion-on-invalid-input

**Comment by certabitmh** [comment]
any news on that?

**Comment by becvert** [comment]
Nope. Closing old issue. Feel free to reopen.
