### ISSUE TITLE
[Android] Black Screen on Suspend/Resume

### ISSUE THREAD

**Issue by manavkumarm** [becvert/cordova-plugin-zeroconf#33]
Hello,

After adding the plugin to our project and flashing the app on an Android device, we are experiencing a black screen when the app is suspended then launched again (hit the Back button till the Home screen is visible, wait for a minute or two then launch the app again) - there is a completely black screen which appears for around 10-15 seconds before the app launches itself again.

The black screen was not appearing before the plugin was added.

Here is the code, used pretty much as-is from the example on the Readme page:

```
$ionicPlatform.ready(function() {

         window.cordova.plugins.zeroconf.watch('_myservice._tcp.', 'local.', function(result) {

          var action = result.action;

          var service = result.service;

          if ('added' === action) {

              $window.alert('$ionicPlatform.ready: Found My service ' + service.name + " at " +
                        service.host + " at " + service.ipv4Addresses[0] + ", Port " + service.port);

          } else {

              $window.alert('$ionicPlatform.ready: Lost My service  ' + service.name + " at " +
                        service.host + " at " + service.ipv4Addresses[0] + ", Port " + service.port);

          }

      });    

}

```

Regards,
Manav

**Comment by becvert** [comment]
no idea. I would look at some debug logs if you can

**Comment by becvert** [comment]
what's up with this?

**Comment by manavkumarm** [comment]
We haven't gotten around to it yet as we are currently focused on the other components of our product. It could be a month or two before we look into it. Will keep you posted.

**Comment by becvert** [comment]
Closing old issue. Feel free to reopen.
