### ISSUE TITLE
Service Announcements delayed on Android

### ISSUE THREAD

**Issue by manavkumarm** [becvert/cordova-plugin-zeroconf#34]
The zeroconf.watch method takes up to 30 seconds-1 minute to receive a service announcement on Android, whereas the announcement is almost instant on iOS. Any idea what might account for the difference in user experience and how it might be resolved?

**Comment by becvert** [comment]
no idea. feel free to review the code. have a look at the underlying libraries too

**Comment by knro** [comment]
I am confused by the "watch" part. Does this work for only NEW services registered _after_ watch is called? or it lists all existing services on the network?

**Comment by becvert** [comment]
Please upgrade to 1.2.5 and try

```
var zeroconf = cordova.plugins.zeroconf;
zeroconf.watchAddressFamily = 'ipv4'; // or 'ipv6' ('any' by default)
```

**Comment by julianCast** [comment]
On version 1.2.6 and adding the ipv4 options.
It still takes about 8 seconds to receive the first service, the rest are inmediate. It looks like is the bonjour connection.
