### ISSUE TITLE
Not finding some services

### ISSUE THREAD

**Issue by julianCast** [becvert/cordova-plugin-zeroconf#37]
Sometimes, it doesnt find all services I have on. I double checked they were on  with with Safari bonjour. After closing zeroconf and opening it several times, it found it.

This happens very often.

Zeroconf 1.2.4 -  Android 7 - ionic 3.3.0

**Comment by becvert** [comment]
Please feel free to review the code. have a look at the underlying libraries too.
I don't have much time right now for further investigations

**Comment by becvert** [comment]
Please upgrade to 1.2.5 and try
