### ISSUE TITLE
Unwatch never send success callback

### ISSUE THREAD

**Issue by britishd** [becvert/cordova-plugin-zeroconf#39]
Hello!

I notice that `unwatch` function never send success callback. 

![never-unwatch](http://screenshots.client-demo-site.net/scn-20170731-160054-hwdfr.png)

My code

`return new Promise((resolve, reject) => this.zeroconf.unwatch(this.config.connection_type,
            this.config.domain,
            (result) => resolve(result),
            (err) => reject(err)));`

Right now I`m using `service.close` for `unwatch`.

**Comment by becvert** [comment]
OK thank you
