### ISSUE TITLE
Android build failed

### ISSUE THREAD

**Issue by wanjungao** [becvert/cordova-plugin-zeroconf#4]
.../platforms/android/src/net/becvert/cordova/ZeroConf.java:32: error: package org.apache.http.conn.util does not exist
import org.apache.http.conn.util.InetAddressUtils;
                                ^
.../platforms/android/src/net/becvert/cordova/ZeroConf.java:381: error: cannot find symbol
                        if (InetAddressUtils.isIPv4Address(sAddr)) {
                            ^
  symbol:   variable InetAddressUtils
  location: class ZeroConf
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
 FAILED

**Comment by wanjungao** [comment]
commented out line 32 //import org.apache.http.conn.util.InetAddressUtils;

and the line 380, change to use instanceof
//String sAddr = addr.getHostAddress().toUpperCase();
                        //if (InetAddressUtils.isIPv4Address(sAddr)) {
                          if (addr instanceof java.net.Inet4Address) {
                            return addr;


Then it can be compiled.

**Comment by becvert** [comment]
Already fixed in the master branch.
