### ISSUE TITLE
[iOS] watch return 'null'

### ISSUE THREAD

**Issue by EnricoGiordano1992** [becvert/cordova-plugin-zeroconf#40]
I wrote this code in Ionic 2 project:
```  
    var zeroconf = (<any>window).cordova.plugins.zeroconf;
    zeroconf.registerAddressFamily = 'ipv4'; // or 'ipv6' ('any' by default)
    zeroconf.watchAddressFamily = 'ipv4'; // or 'ipv6' ('any' by default)
    zeroconf.watch('_myservice._tcp', '.local.',
      function(result:any) {
        console.log("dev:" + JSON.stringify(result));
      },
      function(err:any){
          console.log("err: "+err)
        }
      );
```

This code works on Android (tested), but in iOS doesn't work (it doesn't find my device). In particular, in iOS returns "null" in failure callback. I'm using Xcode 8.3.3 and Swift 3. How can I resolve this? What version of Xcode did you use?

Many thanks!

**Comment by becvert** [comment]
Latest version.
Do you see any error message in the xcode console?
You can enable some debugging with `other swift flags: -D DEBUG`

**Comment by EnricoGiordano1992** [comment]
I've this error:
```
ZeroConf: watch _myservice._tcp.local.
ZeroConf: netServiceBrowser:didNotSearch:(Function) ["NSNetServicesErrorCode": -72004, "NSNetServicesErrorDomain": 10]
2017-08-04 14:24:05.562 Ionic Conference[373:160833] err: null
```

**Comment by becvert** [comment]
it's about the dots I think. must rather be:  `zeroconf.watch('_myservice._tcp.', 'local.',`

**Comment by EnricoGiordano1992** [comment]
thank you, it works!
