### ISSUE TITLE
cordova built error

### ISSUE THREAD

**Issue by amirmatin** [becvert/cordova-plugin-zeroconf#42]
Hi, 

I'm getting a "build error " when building the project for android.. 
"undefined is no a function"
i'm using cordova version 6.1.1 with VS5015...

thanks

**Comment by becvert** [comment]
No idea. Please figure it out and let us know. Thanks

**Comment by amirmatin** [comment]
once the plugin is installed, there are two folder added to the project 
   1) cordova-plugin-add-swift-support
   2) cordova-plugin-zeroconf
the problem seems to be in the swift-support as when I delete it, build is successful and runs fine on android platform however I believe this will cause issues when compiling the app for iOS ?!
can you confirm ?

p.s. a "list" functionality would be very helpful which will list/return all the published mDNS services
thanks
Amir

**Comment by becvert** [comment]
dependency is required for ios.
it should not affect android build.
output some more log if you can with `cordova --verbose` or wihtin VisualStudio
