### ISSUE TITLE
Add plugin failed when npm@5

### ISSUE THREAD

**Issue by NeoLSN** [becvert/cordova-plugin-zeroconf#43]
It will fail because the `cordova-plugin-add-swift-support` dependency.
Maybe you can also add the version in the dependency.

Seems this issue is the same as:
https://github.com/EddyVerbruggen/SocialSharing-PhoneGap-Plugin/pull/849

**Comment by NeoLSN** [comment]
@becvert Could you add this in the plugin xml and also publish a new version?

**Comment by becvert** [comment]
I'll do that when I can 😉

**Comment by becvert** [comment]
I could not reproduce the issue (cordova 7, node 6.11.2, npm 5.4.0):
```
cordova create .
cordova platform add ios
cordova platform add android
cordova plugin add cordova-plugin-zeroconf
```
I'll add the version number anyway because it is good practice.

**Comment by NeoLSN** [comment]
Most of case is caused when restoring platform from repository.

**Comment by becvert** [comment]
release 1.2.7 is online.
please close this issue if it's fine for you.

**Comment by NeoLSN** [comment]
Yes, it worked. Thank you.
