### ISSUE TITLE
Limiting connections

### ISSUE THREAD

**Issue by Dipayon3D** [becvert/cordova-plugin-zeroconf#44]
Is it possible to limit the number of connections to the server? or at least filter out the connections, like accept or decline a connection ??

**Comment by becvert** [comment]
This plugin is about network discovery. 
Is your question about my other plugin websocket-server?
Wsserver does not limit the number of connections. It could be a new feature.
You can call close in the onOpen handler to decline a connection.
Please open an issue with wsserver if you want to follow up that point. thanks

**Comment by Dipayon3D** [comment]
Yes, I ment the server . . . Sorry for this misleading issue . . . I'll open one on the Wsserver . . . :)
