### ISSUE TITLE
[Android] zeroconf.watch Error

### ISSUE THREAD

**Issue by Dipayon3D** [becvert/cordova-plugin-zeroconf#45]
Hi . . .I am trying to use this plugin in an Android app, but whenever I start to watch for server, i get an error saying "Error: setsockopt failed: ENODEV (No such device)" . . . What does it mean and how to fix it ?? By the way, for the server part I'm using cordova-plugin-websocket-server . . . Thanks in advance.

**Comment by becvert** [comment]
did you solve this? is this related to wifi not enbaled?

**Comment by Dipayon3D** [comment]
Not yet . . . I have been busy with other things lately . . . Will get back to it soon .

**Comment by becvert** [comment]
are you in Android AP Mode? [https://github.com/jmdns/jmdns/issues/120](https://github.com/jmdns/jmdns/issues/120)?

**Comment by becvert** [comment]
Please upgrade to 1.2.8 and let me know if it's better

**Comment by Dipayon3D** [comment]
No . . .  Not in Android AP mode . . . I'll try using 1.2.8 very soon . . . I'll be sure to let you know . . .

**Comment by emcniece** [comment]
@Dipayon3D also try disabling cellular data (https://github.com/jmdns/jmdns/issues/116)

**Comment by becvert** [comment]
Closing old issue. Feel free to reopen.
