### ISSUE TITLE
[Android] Nullpointer exception for unwatch

### ISSUE THREAD

**Issue by benjamin-bueckendorf** [becvert/cordova-plugin-zeroconf#48]
Hi,

since upgrading from version 1.2.4 to 1.2.7 android devices cannot find advertised mdns services. Error log gives me the following:

_java.lang.NullPointerException: Attempt to invoke direct method 'void net.becvert.cordova.ZeroConf$BrowserManager.unwatch(java.lang.String, java.lang.String)' on a null object reference
	at net.becvert.cordova.ZeroConf$BrowserManager.access$700(ZeroConf.java:384)
	at net.becvert.cordova.ZeroConf$5.run(ZeroConf.java:276)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)_

I've since gone back to using 1.2.4 again.
Great plugin, hope the above details suffice to solve the issue!

Regards

**Comment by becvert** [comment]
I'll have a look. thanks

**Comment by becvert** [comment]
what's your javascript code?
do you call `unwatch` and `close` at the same time for instance?

**Comment by benjamin-bueckendorf** [comment]
Sequentially, yes:
so after one another I have:

_zeroconf.unwatch('_customtype._tcp.', 'local.');
zeroconf.close();_

**Comment by becvert** [comment]
ok I see where is the problem. It'll be fixed in the next version.
FYI, `close` should `unwatch` all services so you should only need to `close`.

**Comment by benjamin-bueckendorf** [comment]
Great stuff, thanks for the advice!

**Comment by becvert** [comment]
Please upgrade to 1.2.8 and let me know if it's better

**Comment by benjamin-bueckendorf** [comment]
Thanks becvert, works perfectly! (I tested on both iOS and Android). Huge performance difference for Android between 1.2.8 and 1.2.4!

**Comment by becvert** [comment]
Thank you 👍
