### ISSUE TITLE
unwatch crash on android

### ISSUE THREAD

**Issue by lilinfr** [becvert/cordova-plugin-zeroconf#5]
Hi !

You should check browser in unwatch method:
`
 private void unwatch(String type)
{
        if (browser != null)
            browser.removeServiceListener(type, this);
}
`

**Comment by becvert** [comment]
I'll have a look

**Comment by lilinfr** [comment]
Hi !

You might also want to check publisher in the unregister method:

`    private void unregister(String type, String name) {

        if (publisher == null)
            return;
`

**Comment by becvert** [comment]
Fixed!
Thank  you

**Comment by lilinfr** [comment]
Hi (again :))

Is it possible that some concurency issues can happen in unregister method ?

I experienced some exeptions that I had to catch to prevent crash, but it does not seem to be a good idea:

- java.lang.NullPointerException
- java.lang.IllegalStateException
- java.util.concurrent.RejectedExecutionException

**Comment by becvert** [comment]
Maybe have a look directly with [jmdns](https://github.com/jmdns/jmdns)
I'm trying to get my hand on the latest version of this library, 
if they could only update the maven repo that'd be nice!
