### ISSUE TITLE
[iOS] zeroconf.close never invokes success/error callback

### ISSUE THREAD

**Issue by antweb** [becvert/cordova-plugin-zeroconf#52]
The behaviour of zeroconf.close() is inconsistent between Android and iOS. While Android sends a plugin result, iOS does not. As the Android version uses a background thread, it is necessary to rely on the callback to make sure the action has finished.

A simple solution would be to send a success plugin result in iOS as well.

**Comment by becvert** [comment]
ok I'll have a look sometime. thank you

**Comment by emcniece** [comment]
@becvert I can PR today!

**Comment by becvert** [comment]
#53 is fixing the `close` method actually.
I think the same could be apply to `stop` indeed
@emcniece  go ahead with merging this into 1.3.0. thanks 👍
