### ISSUE TITLE
Please update dependency library 'cordova-plugin-add-swift-support' to 1.7.1

### ISSUE THREAD

**Issue by NeoLSN** [becvert/cordova-plugin-zeroconf#59]
Right now, this plugin can't be added success because this issue on dependency library `cordova-plugin-add-swift-support`.
It is already fixed in https://github.com/akofman/cordova-plugin-add-swift-support/issues/43

Can you please update the `cordova-plugin-add-swift-support` library?

**Comment by lrbalt** [comment]
https://github.com/becvert/cordova-plugin-zeroconf/blob/276865500260cdb838e4ce6ef94882e8a1eeac90/plugin.xml#L46

I think that line needs to be updated.

**Comment by becvert** [comment]
done. thank you.

**Comment by lrbalt** [comment]
it works! thanks!
