### ISSUE TITLE
Upgrade cordova-plugin-add-swift-support to 1.7.2

### ISSUE THREAD

**Issue by emcniece** [becvert/cordova-plugin-zeroconf#62]
[cordova-plugin-add-swift-support:1.7.2 changelog](https://github.com/akofman/cordova-plugin-add-swift-support/blob/master/CHANGELOG.md)

Spawned from https://github.com/becvert/cordova-plugin-zeroconf/issues/60

**Comment by NeoLSN** [comment]
I tested. The new swift plugin worked well after upgrade.
