### ISSUE TITLE
Upgrade JmDNS to master branch, test

### ISSUE THREAD

**Issue by emcniece** [becvert/cordova-plugin-zeroconf#63]
This plugin currently specifies JmDNS version 3.5.3, and it may benefit from a fix that is currently applied on master branch.

PR https://github.com/jmdns/jmdns/pull/150 may resolve https://github.com/jmdns/jmdns/issues/116 which may in turn resolve several issues here.

I think that we just need to remove the `:3.5.3` from https://github.com/becvert/cordova-plugin-zeroconf/blob/master/plugin.xml#L28 but confirming that the app builds with the desired branch of JmDNS might be tricky since Maven dependencies are abstracted through Cordova.

**Comment by becvert** [comment]
I'll have a look very soon

**Comment by becvert** [comment]
@emcniece I'm waiting on the results of your testing. 
If we can benefit from this we'll try to move to the master branch.
But I'd rather wait for a JmDNS release. Maybe you could ask for it. Thanks

**Comment by becvert** [comment]
done 👍

**Comment by emcniece** [comment]
Great, thank you! Updated https://github.com/becvert/cordova-plugin-zeroconf/milestone/1 and https://github.com/becvert/cordova-plugin-zeroconf/milestone/2

**Comment by kaikreuzer** [comment]
> it looks like the JmDNS release may take a long time

But no! 3.5.4 is available since today 🎉
