### ISSUE TITLE
Create issue template & add troubleshooting instructions 

### ISSUE THREAD

**Issue by emcniece** [becvert/cordova-plugin-zeroconf#69]
It might be helpful to provide some information to help streamline the assistance process.

Adding a troubleshooting section to the README could be a good start:

- Common network problems
    - Wifi only, Cell data doesn't work
    - Android: try disabling cell data
    - Ad-hoc setup
- 3rd-party Bonjour/mDNS browser apps for testing

We could also create an [issue template](https://blog.github.com/2016-02-17-issue-and-pull-request-templates/) to help prompt users for info that we ask for on a regular basis:

- Operating system(s)
- Code framework (Cordova, Ionic)
- Number of devices in use
- Plugin init'd within `deviceReady`?

@becvert any other common problems/questions you can think of?

**Comment by becvert** [comment]
This is a good idea. I don't have time to devote to this right now though.

**Comment by emcniece** [comment]
No problem. I'm doing a bit of work near here lately, will PR with some initial ideas.

**Comment by becvert** [comment]
Closing old issue. Feel free to reopen.
