### ISSUE TITLE
Use Android's Network Service Discovery (NSD)

### ISSUE THREAD

**Issue by becvert** [becvert/cordova-plugin-zeroconf#7]
NSD is available since Jelly Bean (API 16)

Objective:
Pre-Jelly Bean devices will use [JmDNS](https://github.com/jmdns/jmdns)
Jelly Bean and more recent devices will use [NSD](http://developer.android.com/reference/android/net/nsd/NsdManager.html) by default.

Important notes:
DnsSdTxtRecord support is only enabled since Lollilop (API 21) but does not seem to work.
Possible workaround using [tinydnssd](https://github.com/youviewtv/tinydnssd) 

Todos:
An option to disable NSD altogether

References:
[http://developer.android.com/training/connect-devices-wirelessly/nsd.html](http://developer.android.com/training/connect-devices-wirelessly/nsd.html)
[https://code.google.com/p/android/issues/detail?id=136099](https://code.google.com/p/android/issues/detail?id=136099)

**Comment by NeoLSN** [comment]
https://github.com/andriydruk/RxDNSSD
Can you consider use this library?

**Comment by becvert** [comment]
@NeoLSN thanks for the link.
I'll have a look
But I won't have much time to spend on this right now.

**Comment by becvert** [comment]
@NeoLSN 
see #14, I'll keep you updated

**Comment by becvert** [comment]
I won't implement NSD after all.
Maybe someone else want to give it a shot.
This plugin might rather move toward apple's dnssd at some stage (with or without the Rx paradigm)
