### ISSUE TITLE
Create demo apps for users to test

### ISSUE THREAD

**Issue by emcniece** [becvert/cordova-plugin-zeroconf#70]
Might be useful to have a couple of apps for users to view and test with.

I recently created https://github.com/emcniece/ZeroconfDemo which is a pure Cordova example. It would be nice to have an Ionic example as well.

The app should be able to demonstrate both watching and registering services. 

**ToDo:**

- Create app demo monorepo with platform-specific subdirectories
- Add README build instructions within each platform directories
- Reference troubleshooting instructions on `becvert/cordova-plugin-zeroconf`

**Comment by becvert** [comment]
I think an average developer should be able to understand and apply the instructions in the README. I don't think demos are necessary and for the least I don't want to add demos to this repo. This is stuff that need maintenance too... I want to keep it lightweight. Thanks

**Comment by emcniece** [comment]
Ah, I should have added that to the initial comment - yes I agree that demos should not be part of this repo.

I'm happy to create an external repo and scaffold a few apps. Given how many users raise issues around basic usage of the plugin, having functional examples to point to seems like it would save us some support time.

You're correct, this introduces more maintenance, and I would like to play with a bit of CI for this new repo to help reduce overhead. I'm happy to maintain this outside of here.

@becvert would you accept a PR for adding some external repo links to the README?

**Comment by becvert** [comment]
Closing old issue. Feel free to reopen.
