### ISSUE TITLE
1.3.3 sends empty hostnames

### ISSUE THREAD

**Issue by fttx** [becvert/cordova-plugin-zeroconf#72]
Steps to reproduce:

create a cordova project, add the plugin, add the [watch example of the readme](https://github.com/becvert/cordova-plugin-zeroconf#watchtype-domain-success-failure) inside a `deviceready` callback.

This is the output:
![image](https://user-images.githubusercontent.com/5663423/42241422-c6a45666-7f0a-11e8-873a-e9d448e1080e.png)

While if i revert back to 1.3.2 it works properly:
![image](https://user-images.githubusercontent.com/5663423/42241678-b15f3da6-7f0b-11e8-8498-fefa1c58c6cb.png)

It doesn't happen with all services, for example, i can see the hostname of my printer with v1.3.3.
I use [node_mdns](https://github.com/agnat/node_mdns/blob/f83c39be5278c5bfba664b996b80ab788bd81f30/examples/express_app.js#L12) to announce the service.

**Comment by emcniece** [comment]
1.3.2 - 1.3.3 comparison: https://github.com/becvert/cordova-plugin-zeroconf/compare/0aab272057eeee4bdb4eb81e633b5093d203012a...3669c917571fbb56c6ebd841b00527ee9ade8233

This may be a problem with `jmdns:3.5.4`, needs investigation.

**Comment by emcniece** [comment]
https://github.com/jmdns/jmdns/milestone/6?closed=1 does not appear to have anything that should cause a situation like this. 

Is it possible that the pure-IPv6 resolution (example 1, v1.3.3) behaves different than the IPv4 resolution (example 2, v1.3.2)?

@fttx do you get different results if you force watching for IPv4?

```js
zeroconf.watchAddressFamily = 'ipv4';
zeroconf.watch('_http._tcp.', 'local.', function(result) {
...
```

**Comment by fttx** [comment]
Nope, still empty hostname

**Comment by emcniece** [comment]
Ok - does the hostname show up in an external Bonjour browser application? ([Mac](http://www.tildesoft.com/)/[Win](https://hobbyistsoftware.com/bonjourbrowser))

**Comment by fttx** [comment]
Yes, it does 
![image](https://user-images.githubusercontent.com/5663423/42243685-703e7402-7f12-11e8-9e7c-4df62d302727.png)

**Comment by emcniece** [comment]
Hmm... I'm running out of ideas. Do you have any other mobile devices you could test the app on?

**Comment by becvert** [comment]
Closing old issue. Feel free to reopen.

**Comment by fttx** [comment]
Sorry to bother you again, but the bug is still there, and it is related to jmdns. 
There is a pull request from the past year: https://github.com/jmdns/jmdns/pull/165

**Comment by emcniece** [comment]
Thank you for finding the root cause! @becvert maybe we should keep this open until jmdns/jmdns#165 is merged.
