### ISSUE TITLE
Cannot find Windows Bonjour Service

### ISSUE THREAD

**Issue by arget888** [becvert/cordova-plugin-zeroconf#73]
Hi,
I have installed Bonjour PrinterService on Windows. I can connect to my WebServer by typing "Markus-PC.local" into the browser of my IPhone or my IPad but if I use the watch function of the plugin i can only see the printer in the network and not my windows pc. What did I have to do to see my Windows PC?
(I also cant see it with a mDNS Browser App from the AppStore)

**Comment by emcniece** [comment]
Can you share some code? Not being able to see the target with a browser app is a bad sign.

**Comment by becvert** [comment]
Closing old issue. Feel free to reopen.
