### ISSUE TITLE
stop loading node modules into our apps with 3d party plugs

### ISSUE THREAD

**Issue by julientype** [becvert/cordova-plugin-zeroconf#91]
plugins are java api to one java-script to control it by one file hook not ,,,,,node modules...   
Stay out out of our  cordova  file folders..... 
Java API  
https://developer.android.com/reference
cordova plugins has nothing to do with node modules 
C type libs or jar all ok but not NODE modals

**Comment by emcniece** [comment]
Hello! This plugin matches your description: it is an API to a single Javascript file and doesn't involve node modules. Could you please link a good example for us to learn from?

**Comment by julientype** [comment]
take a look 
ZeroConf-Bridging-Header.h
it installs  hooks and 3d party plugin.....
plugin are simple.. its encapsulated JAVA api to hook to one script
 it should not implant bridges
you want clean JAVA 
It installs cordova-plugin-webview-switch
this plugin will install modules to cordova  why?
plugins have nothing to do with JavaScript but JAVA only

**Comment by emcniece** [comment]
[ZeroConf-Bridging-Header.h](https://github.com/becvert/cordova-plugin-zeroconf/blob/master/src/ios/ZeroConf-Bridging-Header.h) is in the iOS directory and is needed for Swift support. It has nothing to do with Java.

I don't understand where "cordova-plugin-webview-switch" is coming from, can you clarify this?

Cordova plugins are designed to work with more than just Java.
